"""
Infographic schemas for request/response validation.

Defines the structure for infographic generation and display.
"""
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


# =============================================================================
# Infographic Structure Schemas (for JSON storage and LLM output)
# =============================================================================

class InfographicSection(BaseModel):
    """A single section in an infographic."""
    id: str = Field(..., description="Unique section identifier")
    heading: str = Field(..., description="Section heading/title")
    icon_hint: Optional[str] = Field(
        None,
        description="Icon hint (e.g., 'lightbulb', 'chart', 'target', 'users', 'shield', 'clock')"
    )
    color_hint: Optional[str] = Field(
        None,
        description="Color hint (e.g., 'primary', 'secondary', 'accent', 'warning', 'success')"
    )
    key_points: List[str] = Field(
        default_factory=list,
        description="Key points or bullet items for this section"
    )
    detail: Optional[str] = Field(
        None,
        description="Optional detailed explanation"
    )
    # Image generation fields
    image_prompt_en: Optional[str] = Field(
        None,
        description="English prompt for image generation (flat infographic style)"
    )
    image_url: Optional[str] = Field(
        None,
        description="URL to the generated image for this section"
    )


class InfographicStructure(BaseModel):
    """Complete infographic structure as generated by LLM."""
    title: str = Field(..., description="Main infographic title")
    subtitle: Optional[str] = Field(None, description="Optional subtitle")
    sections: List[InfographicSection] = Field(
        ...,
        min_length=1,
        max_length=10,
        description="Infographic sections (3-6 recommended)"
    )
    footer_note: Optional[str] = Field(
        None,
        description="Optional footer note (e.g., source attribution)"
    )


# =============================================================================
# API Request/Response Schemas
# =============================================================================

class InfographicCreateRequest(BaseModel):
    """Request schema for creating a new infographic."""
    topic: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Topic or prompt describing what the infographic should cover"
    )
    source_ids: List[str] = Field(
        default_factory=list,
        description="Source IDs to use for context. Empty means all sources in notebook."
    )
    style_preset: str = Field(
        "default",
        description="Style preset for the infographic"
    )


class InfographicResponse(BaseModel):
    """Response schema for a complete infographic."""
    id: str
    notebook_id: str
    title: str
    topic: Optional[str] = None
    structure: InfographicStructure
    style_preset: str = "default"
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class InfographicListItem(BaseModel):
    """Response schema for listing infographics (without full structure)."""
    id: str
    notebook_id: str
    title: str
    topic: Optional[str] = None
    style_preset: str = "default"
    created_at: datetime

    class Config:
        from_attributes = True


class InfographicListResponse(BaseModel):
    """Response schema for listing infographics."""
    infographics: List[InfographicListItem]
    total: int
