"""
Slide deck schemas for request/response validation.

Defines the structure for slide generation and PPTX export.
"""
from datetime import datetime
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


# =============================================================================
# Slide Structure Schemas (for JSON storage and LLM output)
# =============================================================================

class SlideData(BaseModel):
    """A single slide in a slide deck."""
    slide_number: int = Field(..., ge=1, description="Slide number (1-indexed)")
    layout: Literal["title", "content", "section", "two_column", "blank"] = Field(
        "content",
        description="Slide layout type"
    )
    title: str = Field(..., description="Slide title")
    subtitle: Optional[str] = Field(None, description="Subtitle (mainly for title slides)")
    bullets: Optional[List[str]] = Field(
        None,
        description="Bullet points for the slide content"
    )
    speaker_notes: Optional[str] = Field(
        None,
        description="Speaker notes for this slide"
    )
    visual_hint: Optional[str] = Field(
        None,
        description="Visual hint (e.g., 'bar chart showing growth', 'diagram of workflow')"
    )
    # Image generation fields
    image_prompt_en: Optional[str] = Field(
        None,
        description="English prompt for image generation (presentation style)"
    )
    image_url: Optional[str] = Field(
        None,
        description="URL to the generated image for this slide"
    )


class SlideOutline(BaseModel):
    """Complete slide deck outline as generated by LLM."""
    title: str = Field(..., description="Presentation title")
    slides: List[SlideData] = Field(
        ...,
        min_length=1,
        max_length=30,
        description="Slides in the presentation"
    )


# =============================================================================
# API Request/Response Schemas
# =============================================================================

class SlideDeckCreateRequest(BaseModel):
    """Request schema for creating a new slide deck."""
    topic: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Topic or prompt describing what the presentation should cover"
    )
    source_ids: List[str] = Field(
        default_factory=list,
        description="Source IDs to use for context. Empty means all sources in notebook."
    )
    target_slides: int = Field(
        8,
        ge=3,
        le=20,
        description="Target number of slides (3-20)"
    )


class SlideDeckResponse(BaseModel):
    """Response schema for a complete slide deck."""
    id: str
    notebook_id: str
    title: str
    topic: Optional[str] = None
    outline: SlideOutline
    slide_count: int
    pptx_available: bool = False
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class SlideDeckListItem(BaseModel):
    """Response schema for listing slide decks (without full outline)."""
    id: str
    notebook_id: str
    title: str
    topic: Optional[str] = None
    slide_count: int
    pptx_available: bool = False
    created_at: datetime

    class Config:
        from_attributes = True


class SlideDeckListResponse(BaseModel):
    """Response schema for listing slide decks."""
    slide_decks: List[SlideDeckListItem]
    total: int
